Resources:
  EC2Instance1:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-03aefa83246f44ef2
      InstanceType: t2.micro
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
  EC2Instance2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-03aefa83246f44ef2
      InstanceType: t2.micro
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Instance Security Group"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0



    
    
    
    
    
    
    
   









