AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  StackName:
    Type: String
    Default: DeepLearnProject

Resources:
  ECSClusterName:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub "${StackName}-ECSClusterName"

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for MyInstances
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  ECSClusterInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref ECSClusterRole

  ECSClusterRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ECSClusterRolePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecs:RegisterContainerInstance
                Resource: "*"

  MyInstance1:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-07151644aeb34558a
      InstanceType: t2.micro
      SecurityGroupIds:
        - !Ref MySecurityGroup
      IamInstanceProfile: !Ref ECSClusterInstanceProfile
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          echo "This is user data for instance 1"
          echo "Register instance 1 to ECS cluster"
          INSTANCE_ID=$(curl http://169.254.169.254/latest/meta-data/instance-id)
          aws ecs register-container-instance --cluster !ImportValue ECSClusterNameExport --container-instance-id $INSTANCE_ID

  MyInstance2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-07151644aeb34558a
      InstanceType: t2.micro
      SecurityGroupIds:
        - !Ref MySecurityGroup
      IamInstanceProfile: !Ref ECSClusterInstanceProfile
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          echo "This is user data for instance 2"
          echo "Register instance 2 to ECS cluster"
          INSTANCE_ID=$(curl http://169.254.169.254/latest/meta-data/instance-id)
          aws ecs register-container-instance --cluster !ImportValue ECSClusterNameExport --container-instance-id $INSTANCE_ID





