Resources:
  MyCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: Livero
      
      
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for instances
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          
  ContainerInstances:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-03aefa83246f44ef2 
      InstanceType: t2.micro
      KeyName: deployfromgithub
      NetworkInterfaces:
        - AssociatePublicIpAddress: 'true'
          DeviceIndex: '0'
          GroupSet:
            - Ref: InstanceSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          echo ECS_CLUSTER=${MyCluster} >> /etc/ecs/ecs.config
  
Outputs:
  MyClusterArn:
    Value: !GetAtt MyCluster.Arn
