AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: DeepLearnProject

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  EC2Instance1:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-01a7573bb17a45f12
      InstanceType: t2.micro
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          apt-get update
          apt-get install -y software-package
          echo "ECS_CLUSTER=DeepLearnProject" >> /etc/ecs/ecs.config

  EC2Instance2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-01a7573bb17a45f12
      InstanceType: t2.micro
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          apt-get update
          apt-get install -y software-package
          echo "ECS_CLUSTER=DeepLearnProject" >> /etc/ecs/ecs.config














    
    
    
    
    
    
    
   









