Resources:
  TaskDefinition:
    Type: "AWS::ECS::TaskDefinition"
    Properties:
      ContainerDefinitions:
        - Name: "web"
          Image: "nginx"
          PortMappings:
            - ContainerPort: 80
          Memory: 512
          Cpu: 256
      Family: "justfamily"
      NetworkMode: "bridge"
      RequiresCompatibilities:
        - "EC2"
  Cluster:
    Type: "AWS::ECS::Cluster"
  Service1:
    Type: "AWS::ECS::Service"
    Properties:
      Cluster: !Ref Cluster
      DesiredCount: 1
      TaskDefinition: !Ref TaskDefinition
      LaunchType: "EC2"
      LoadBalancers:
        - ContainerName: "web"
          ContainerPort: 80
          TargetGroupArn: !Ref TargetGroup1
      PlacementStrategies:
        - Type: "random"
      PlacementConstraints:
        - Type: "distinctInstance"
      SchedulingStrategy: "REPLICA"
  Service2:
    Type: "AWS::ECS::Service"
    Properties:
      Cluster: !Ref Cluster
      DesiredCount: 1
      TaskDefinition: !Ref TaskDefinition
      LaunchType: "EC2"
      LoadBalancers:
        - ContainerName: "web"
          ContainerPort: 80
          TargetGroupArn: !Ref TargetGroup2
      PlacementStrategies:
        - Type: "random"
      PlacementConstraints:
        - Type: "distinctInstance"
      SchedulingStrategy: "REPLICA"
  TargetGroup1:
    Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
    Properties:
      Name: "target-group-1"
      Port: 80
      Protocol: "HTTP"
      TargetType: "ip"
      VpcId: !Ref VPC
  TargetGroup2:
    Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
    Properties:
      Name: "target-group-2"
      Port: 80
      Protocol: "HTTP"
      TargetType: "ip"
      VpcId: !Ref VPC





