Resources:
  Service1:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref Livero
      DesiredCount: 1
      LaunchType: EC2
      TaskDefinition: !Ref ecsproj
  Service2:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref Livero
      DesiredCount: 1
      LaunchType: EC2
      TaskDefinition: !Ref ecsproj2
  TaskDefinition1:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Name: nodi1
          Image: nginx:latest
          PortMappings:
            - ContainerPort: 80
              HostPort: 80
      Cpu: '256'
      Memory: '512'
      Family: justaskfamily1
  TaskDefinition2:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Name: nodi2
          Image: nginx:latest
          PortMappings:
            - ContainerPort: 80
              HostPort: 80
      Cpu: '256'
      Memory: '512'
      Family: justaskfamily2
Outputs:
  Service1Endpoint:
    Value: !Join ['', ['http://', !GetAtt Service1.LoadBalancers[0].DNSName]]
  Service2Endpoint:
    Value: !Join ['', ['http://', !GetAtt Service2.LoadBalancers[0].DNSName]]
