Resources:
  MyCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: livero
  MyService1:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref MyCluster
      DesiredCount: 1
      LaunchType: EC2
      TaskDefinition: !Ref MyTaskDefinition1
  MyService2:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref MyCluster
      DesiredCount: 1
      LaunchType: EC2
      TaskDefinition: !Ref MyTaskDefinition2
  MyTaskDefinition1:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Name: nodi1
          Image: nginx:latest
          PortMappings:
            - ContainerPort: 80
              HostPort: 80
      Cpu: '256'
      Memory: '512'
      Family: justaskfamily1
  MyTaskDefinition2:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Name: nodi2
          Image: nginx:latest
          PortMappings:
            - ContainerPort: 80
              HostPort: 80
      Cpu: '256'
      Memory: '512'
      Family: justaskfamily2
Outputs:
  MyService1Endpoint:
    Value: !Join ['', ['http://', !GetAtt MyService1.LoadBalancers{{0}}.DNSName]]
  MyService2Endpoint:
    Value: !Join ['', ['http://', !GetAtt MyService2.LoadBalancers{{0}}.DNSName]]


