Resources:
  TaskDefinition1:
    Type: "AWS::ECS::TaskDefinition"
    Properties:
      ContainerDefinitions:
        - Name: "web"
          Image: "nginx"
          PortMappings:
            - ContainerPort: 80
          Memory: 0.5GB
          Cpu: 256
      Family: "justfamily1"
      NetworkMode: "bridge"
      RequiresCompatibilities:
        - "EC2"

  TaskDefinition2:
    Type: "AWS::ECS::TaskDefinition"
    Properties:
      ContainerDefinitions:
        - Name: "simple-task"
          Image: "hello-world"
          Memory: 0.5GB
          Cpu: 256
      Family: "justfamily2"
      NetworkMode: "bridge"
      RequiresCompatibilities:
        - "EC2"

  Cluster:
    Type: "AWS::ECS::Cluster"

  Service1:
    Type: "AWS::ECS::Service"
    Properties:
      Cluster: !Ref Cluster
      DesiredCount: 1
      TaskDefinition: !Ref TaskDefinition1
      LaunchType: "EC2"
      SchedulingStrategy: "REPLICA"

  Service2:
    Type: "AWS::ECS::Service"
    Properties:
      Cluster: !Ref Cluster
      DesiredCount: 1
      TaskDefinition: !Ref TaskDefinition2
      LaunchType: "EC2"
      SchedulingStrategy: "REPLICA"
