Resources:
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: livero
  Service1:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref Cluster
      DesiredCount: 1
      LaunchType: EC2
      TaskDefinition: !Ref TaskDefinition1
  Service2:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref Cluster
      DesiredCount: 1
      LaunchType: EC2
      TaskDefinition: !Ref TaskDefinition2
  TaskDefinition1:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Name: nodi1
          Image: nginx:latest
          PortMappings:
            - ContainerPort: 80
              HostPort: 80
      Cpu: '256'
      Memory: '512'
      Family: justaskfamily1
  TaskDefinition2:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Name: nodi2
          Image: nginx:latest
          PortMappings:
            - ContainerPort: 80
              HostPort: 80
      Cpu: '256'
      Memory: '512'
      Family: justaskfamily2



