Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: "Boom"

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Name: "my-container"
          Image: "nginx"
          PortMappings:
            - ContainerPort: 80
          Memory: 512
          Cpu: 256
      Family: "my-task-family"
      NetworkMode: "bridge"
      RequiresCompatibilities:
        - "EC2"

  Service:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ECSCluster
      DesiredCount: 1
      TaskDefinition: !Ref TaskDefinition
      LaunchType: "EC2"
      SchedulingStrategy: "REPLICA"








      
 
