AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  StackName:
    Type: String
    Default: DeepLearnProject

Resources:
  ECSClusterName:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub "${StackName}-ECSClusterName"

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for MyInstances
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  MyInstance1:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-07151644aeb34558a
      InstanceType: t2.micro
      SecurityGroupIds:
        - !Ref MySecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          echo "ECS_CLUSTER=${ECSClusterName}" >> /etc/ecs/ecs.config
          echo "ECS_BACKEND_HOST=169.254.170.2" >> /etc/ecs/ecs.config
          echo "ECS_BACKEND_PORT=80" >> /etc/ecs/ecs.config
          start ecs

  MyInstance2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-07151644aeb34558a
      InstanceType: t2.micro
      SecurityGroupIds:
        - !Ref MySecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          echo "ECS_CLUSTER=${ECSClusterName}" >> /etc/ecs/ecs.config
          echo "ECS_BACKEND_HOST=169.254.170.2" >> /etc/ecs/ecs.config
          echo "ECS_BACKEND_PORT=80" >> /etc/ecs/ecs.config
          start ecs

Outputs:
  ECSClusterNameOutput:
    Value: !Ref ECSClusterName
    Export:
      Name: ECSClusterName


