Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: "DeepLearnProject"

  ContainerInstance1:
    Type: AWS::ECS::ContainerInstance
    Properties:
      Cluster: !Ref ECSCluster
      InstanceType: t2.micro
      Tags:
        - Key: Name
          Value: ContainerInstance1

  ContainerInstance2:
    Type: AWS::ECS::ContainerInstance
    Properties:
      Cluster: !Ref ECSCluster
      InstanceType: t2.micro
      Tags:
        - Key: Name
          Value: ContainerInstance2






    
    
    
    
    
    
    
   









