AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  StackName:
    Type: String
    Default: DeepLearnProject

Resources:
  ECSClusterName:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub "${StackName}-ECSClusterName"

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for MyInstances
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  MyInstance1:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-07151644aeb34558a
      InstanceType: t2.micro
      SecurityGroupIds:
        - !Ref MySecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          echo "This is user data for instance 1"
          echo "Registering instance 1 to ECS cluster"
          INSTANCE_ID=$(curl http://169.254.169.254/latest/meta-data/instance-id)
          REGISTER_OUTPUT=$(aws ecs create-container-instance --cluster !Ref ECSClusterName --instance-id $INSTANCE_ID)
          echo "Registration output:"
          echo $REGISTER_OUTPUT

  MyInstance2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-07151644aeb34558a
      InstanceType: t2.micro
      SecurityGroupIds:
        - !Ref MySecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          echo "This is user data for instance 2"
          echo "Registering instance 2 to ECS cluster"
          INSTANCE_ID=$(curl http://169.254.169.254/latest/meta-data/instance-id)
          REGISTER_OUTPUT=$(aws ecs create-container-instance --cluster !Ref ECSClusterName --instance-id $INSTANCE_ID)
          echo "Registration output:"
          echo $REGISTER_OUTPUT
Outputs:
  ECSClusterNameOutput:
    Value: !Ref ECSClusterName
    Export:
      Name: ECSClusterName


