Resources:
  MyService1:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref Livero
      DesiredCount: 1
      LaunchType: EC2
      TaskDefinition: !Ref ecsproj
  MyService2:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref Livero
      DesiredCount: 1
      LaunchType: EC2
      TaskDefinition: !Ref ecsproj2
  MyTaskDefinition1:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Name: node1
          Image: nginx:latest
          PortMappings:
            - ContainerPort: 80
              HostPort: 80
      Cpu: '256'
      Memory: '512'
      Family: justaskfamily1
  MyTaskDefinition2:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Name: node2
          Image: nginx:latest
          PortMappings:
            - ContainerPort: 80
              HostPort: 80
      Cpu: '256'
      Memory: '512'
      Family: justaskfamily2
Outputs:
  MyService1Endpoint:
    Value: !Join ['', ['http://', !GetAtt Justservice1.LoadBalancers[0].DNSName]]
  MyService2Endpoint:
    Value: !Join ['', ['http://', !GetAtt Justservice2.LoadBalancers[0].DNSName]]
