AWSTemplateFormatVersion: 2010-09-09
Description: Create an S3 bucket with an index.html file and a CloudFront distribution

Parameters:
  BucketName:
    Type: String
    Description: S3 bucket name
    Default: shadowbowl
  GitHubToken:
    Type: String
    Description: GitHub access token
    NoEcho: true
  GitHubRepo:
    Type: String
    Description: GitHub repository name (owner/repo)
    Default: ShadowOpsCross/ThatsIT
  GitHubBranch:
    Type: String
    Description: GitHub repository branch
    Default: master

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action:
              - s3:GetObject
            Resource: !Join ['', ['arn:aws:s3:::', !Ref S3Bucket, '/*']]  

  MyS3Object:
    Type: "AWS::CloudFormation::WaitConditionHandle"

  UploadS3Object:
    Type: "AWS::CloudFormation::Stack"
    DependsOn: S3BucketPolicy
    Properties:
      TemplateURL: "https://s3-eu-central-1.amazonaws.com/cloudformation-templates-eu-central-1/WaitCondition_S3.template"
      Parameters:
        SourceBucket: !Ref S3Bucket
        SourceObject: "index.html"
        SourceContent: !Sub |
          #!/bin/bash
          cd /opt
          mkdir www
          cd www
          aws s3 cp https://raw.githubusercontent.com/${GitHubRepo}/${GitHubBranch}/.github/workflows/index.html index.html
      NotificationARNs:
        - !Ref MyS3Object

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt [S3Bucket, DomainName]
            Id: S3BucketOrigin
            S3OriginConfig:
              OriginAccessIdentity: ''
        DefaultRootObject: index.html
        Enabled: true
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          TargetOriginId: S3BucketOrigin
          ForwardedValues:
            QueryString: false
          ViewerProtocolPolicy: redirect-to-https
        ViewerCertificate:
          CloudFrontDefaultCertificate: true



