---
AWSTemplateFormatVersion: '2010-09-09'
---  
Parameters:
  BucketName:
    Type: String
    Description: shadowbowl
  GitHubUsername:
    Type: String
    Description: ShadowOpsCross
  GitHubRepository:
    Type: String
    Description: ThatsIT
  GitHubBranch:
    Type: String
    Description: master
  GitHubDirectory:
    Type: String
    Description: /.github/workflows/

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName

  MyBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MyS3Bucket
      PolicyDocument:
        Statement:
          - Sid: AllowPublicRead
            Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref MyS3Bucket
                - '/*'

  MyCodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: MyCodePipeline
      Stages:
        - Name: Source
          Actions:
            - Name: GitHubSourceAction
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              Configuration:
                Owner: !Ref GitHubUsername
                Repo: !Ref GitHubRepository
                Branch: !Ref GitHubBranch
                OAuthToken: !Ref GitHubOAuthToken
                PollForSourceChanges: false
              OutputArtifacts:
                - Name: SourceOutput
              RunOrder: 1
        - Name: Deploy
          Actions:
            - Name: S3DeployAction
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: S3
                Version: 1
              Configuration:
                BucketName: !Ref MyS3Bucket
                Extract: 'true'
                ObjectKey: index.html
              InputArtifacts:
                - Name: SourceOutput
              RunOrder: 1

  MyCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: CloudFront distribution for my website
        Aliases:
          - my-domain-name.example.com
        DefaultRootObject: index.html
        Origins:
          - Id: MyS3BucketOrigin
            DomainName: !GetAtt MyS3Bucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: ''
        DefaultCacheBehavior:
          TargetOriginId: MyS3BucketOrigin
          ViewerProtocolPolicy: allow-all
        PriceClass: PriceClass_100
        HttpVersion: http2
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
        Enabled: true

Outputs:
  CloudFrontURL:
    Value: !Sub "http://${MyCloudFrontDistribution.DomainName}"
    Description: CloudFront URL





