AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0749e2c902c836c08  # ID образу Amazon Linux 2
      InstanceType: t2.micro  # Оберіть потрібний тип EC2 інстансу
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y  # Оновити систему
          yum install -y docker  # Встановити Docker
          service docker start  # Запустити сервіс Docker
          docker run -d -p 80:80 nginx  # Запустити контейнер Nginx на порту 80
  MyEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref MyEC2Instance  # Пов'язати Elastic IP з MyEC2Instance
  MyEIPAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      AllocationId: !GetAtt MyEIP.AllocationId  # Отримати Allocation ID для Elastic IP
      InstanceId: !Ref MyEC2Instance  # Пов'язати Elastic IP з MyEC2Instance
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP access
      VpcId: !Sub |
        `aws ec2 describe-vpcs --query "Vpcs[0].VpcId" --output text`  # Отримати ідентифікатор VPC автоматично
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:  # Правила для вихідного трафіку
        - IpProtocol: '-1'  # Дозволити весь вихідний трафік
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: MySecurityGroup


