AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0749e2c902c836c08  # ID of the Amazon Linux 2 image
      InstanceType: t2.micro  # Choose your desired EC2 instance type
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y  # Update the system
          yum install -y docker  # Install Docker
          service docker start  # Start the Docker service
          docker run -d -p 80:80 nginx  # Run the Nginx container on port 80
  MyEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref MyEC2Instance  # Associate the Elastic IP with MyEC2Instance
  MyEIPAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      AllocationId: !GetAtt MyEIP.AllocationId  # Get the Allocation ID for the Elastic IP
      InstanceId: !Ref MyEC2Instance  # Associate the Elastic IP with MyEC2Instance
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:  # Outbound traffic rules
        - IpProtocol: '-1'  # Allow all outbound traffic
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: MySecurityGroup

