name: Auto Build and Push Image with hashtag

on:
  push:
    branches:
      - master
  workflow_dispatch:
    

      
jobs:
  build_and_push_docker_image:
    name:  Auto Build and Push
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    - name: Install Trivy
      run: |
          sudo apt-get update
          sudo apt-get install wget apt-transport-https gnupg lsb-release -y
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy -y
    - name: Build the Docker image
      run: |
        docker image build -t shadowcrosstwink/registry:${{ github.sha }} .
    - name: Scan Docker image
      run: |
          trivy image shadowcrosstwink/registry:${{ github.sha }} --format json > trivy_report.json
    - name: Push the Docker image
      run: |
        docker push shadowcrosstwink/registry:${{ github.sha }}
   


    - name: Upload Trivy Report to DockerHub artifacts
      uses: docker/build-push-action@v2
      with:
          context: .
          push: false
          tags:  shadowcrosstwink/registry:${{ github.sha }}
          outputs: |
            path=trivy_report.json
          labels: |
            trivy_report=true
