name: Build and Push Docker Image

on:
  push:
    branches:
      - master
  workflow_dispatch:
  
env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
jobs:
  build_and_push_docker_image:
    name: PUSH
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
      
    - name: Login to Docker Hub
      uses: actions/docker/login@master
      with:
       DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
       DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
       
    - name: Test
      run: mvn clean verify -U
    - name: build
      run: ./mvnw compile jib:dockerBuild
    - name: push
      run:  docker push odfsoft/guess-game:latest
      

  manual_build_and_push_docker_image:
    name: Manual Build and Push Docker Image
    needs: []
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ github.repository }}:${{ github.event.inputs.tag }}
      if: github.event_name == 'workflow_dispatch'
      env:
        INPUT_TAG: ${{ github.event.inputs.tag }}
    - uses: actions/checkout@v1
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
