name: Build and Push Docker Image

on:
  push:
    branches:
      - master
  workflow_dispatch:
  
env:
          DOCKER_USERNAME:      ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD:      ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_ACCESS_TOKEN:  ${{ secrets.DOCKER_ACCESS_TOKEN }}

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: TEST secrets
        run: echo ${{ secrets.DOCKER_USERNAME }} & echo ${{ secrets.DOCKER_PASSWORD }} & echo ${{ secrets.DOCKER_ACCESS_TOKEN }}
     
       
      - name: Test
        run: mvn clean verify -U
      - name: build
        run: ./mvnw compile jib:dockerBuild
      - name: push
        run:  docker push odfsoft/guess-game:latest
      

  manual_build_and_push_docker_image:
    name: Manual Build and Push Docker Image
    needs: []
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username:       ${{ secrets.DOCKER_USERNAME }}
        password:       ${{ secrets.DOCKER_ACCESS_TOKEN }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ github.repository }}:${{ github.event.inputs.tag }}
      if: github.event_name == 'workflow_dispatch'
      env:
        INPUT_TAG: ${{ github.event.inputs.tag }}
    - uses: actions/checkout@v1
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
