Parameters:
  GitHubUser:
    Type: String
    Default: ShadowOpsCross 
    Description: GitHub username
  GitHubRepo:
    Type: String
    Default: ThatsIT
    Description: GitHub repository name
  GitHubBranch:
    Type: String
    Default: master
    Description: GitHub repository branch name

  Resources:
    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: shadowbowlen
        AccessControl: PublicRead

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Join [ '', [ "arn:aws:s3:::", !Ref S3Bucket, "/*" ] ]

  S3BucketIndexObject:
    Type: AWS::S3::Object
    Properties:
      Bucket: !Ref S3Bucket
      Key: index.html
      ContentType: text/html
      Source: https://raw.githubusercontent.com/${GitHubUser}/${GitHubRepo}/${GitHubBranch}/index.html

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt [S3Bucket, DomainName]
            Id: S3BucketOrigin
            S3OriginConfig:
              OriginAccessIdentity: ""
        DefaultRootObject: index.html
        Enabled: true
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          TargetOriginId: S3BucketOrigin
          ForwardedValues:
            QueryString: false
          ViewerProtocolPolicy: redirect-to-https
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
