name: Deploy to S3 and EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
      - name: Deploy to S3
        run: |
          aws s3 cp index.html s3://shadowbowl
          echo 'index.html file copied to S3 bucket.'
      - name: Install SSH
        run: |
          sudo apt-get update
          sudo apt-get install -y ssh
      - name: Copy index.html to EC2
        run: |
          chmod 400 deployfromgithub.pem
          scp -o "StrictHostKeyChecking=no" -i deployfromgithub.pem index.html ubuntu@ec2-3-73-130-117.eu-central-1.compute.amazonaws.com
