name: Deploy to S3 Bucket and Launch on EC2
on:
  push:
    branches:
      - master
jobs:
  deploy:
   runs-on: ubuntu-latest
   steps:
       - name: Checkout
         uses: actions/checkout@v2
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v1
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
           aws-region:  eu-central-1 
       - name: Set up SSH key
         run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_PUBLIC_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
       - name: SSH to AWS Instance
         run: |
          chmod 400 deployfromgithub.pem
          ssh -i ~/.ssh/id_rsa ec2-3-76-212-173.eu-central-1.compute.amazonaws.com 'echo "Hello, world!"'
