name: Deploy CloudFormation Stack

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        sudo pip3 install awscli

    - name: Deploy CloudFormation stack
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_REGION: eu-central-1
        STACK_NAME: "mini-civilization"
        TEMPLATE_URL: "https://raw.githubusercontent.com/ShadowOpsCross/ThatsIT/master/.github/workflows/cloudshadows3.yml"
      run: |
        aws cloudformation create-stack \
          --stack-name $STACK_NAME \
          --template-url $TEMPLATE_URL \
          --capabilities CAPABILITY_NAMED_IAM
