name: Deploy AWS EC2 Instance

on:
  push:
    branches:
     - master
     - test

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: eu-central-1

          
      - name: Deploy Ubuntu EC2
        run: |
          aws cloudformation deploy \
          --stack-name ubuntu-ec2 \
          --template-file CloudFormation/ec2_instance.yml \
          --capabilities CAPABILITY_NAMED_IAM
