name: Deploy CloudFormation Stack

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI
        uses: aws-actions/configure-aws-cli@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: eu-central-1

      - name: Validate CloudFormation Template
        run: |
          aws cloudformation validate-template --template-body file://workflows/deploytos3.yml
/


      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy --stack-name <stack-name> --template-file workflows/deploytos3.yml --capabilities CAPABILITY_NAMED_IAM
