name: Deploy website

on:
  push:
    branches:
     - master 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: eu-central-1

      - name: Install or Update AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
          
      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
          --stack-name LINDEMANN \
          --template-file cloudfront.yml \
          --capabilities CAPABILITY_NAMED_IAM
          
      - name: Copy index.html to S3 bucket
        run: |
          aws s3 cp .github/workflows/index.html s3://shadowbowl
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
          --distribution-id arn:aws:cloudfront::*:distribution/* \
          --paths "/*"


