name: Deploy to S3 Bucket and Launch on EC2
on:
  push:
    branches:
      - master
jobs:
  deploy:
   runs-on: ubuntu-latest
   steps:
       - name: Checkout
         uses: actions/checkout@v2
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v1
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
           aws-region:  eu-central-1 
       - name: Create SSH directory
         run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

       - name: Install SSH key
         run: echo "${{ secrets.deployfromgithub.pem }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa

       - name: Add EC2 host to known_hosts
         run: ssh-keyscan -H 18.156.128.237 >> ~/.ssh/known_hosts

       - name: Deploy to EC2
         run: ssh -o StrictHostKeyChecking=no -i ~/.ssh ubuntu@e3.73.130.117 'cd . && nohup python -m http.server 80 > /dev/null 2>&1 &'
