name: loperamid

on:
  push:
    branches:
     - master 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout коду
        uses: actions/checkout@v2

      - name: Налаштування облікових даних AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: eu-central-1

      - name: Створення EC2 інстансів
        id: створення-інстансів
        run: |
          aws cloudformation deploy \
          --stack-name my-instances-stack \
          --template-file cfecs.yml \
          --capabilities CAPABILITY_NAMED_IAM

      - name: Очікування завершення створення EC2 інстансів
        run: |
          aws cloudformation wait stack-create-complete --stack-name my-instances-stack

      - name: Отримання ідентифікаторів EC2 інстансів
        id: отримання-ідентифікаторів-інстансів
        run: |
          id1=$(aws cloudformation describe-stacks --stack-name my-instances-stack --query 'Stacks[0].Outputs[?OutputKey==`EC2Instance1`].OutputValue' --output text)
          echo "instance_id_1=$id1" >> $GITHUB_ENV
          id2=$(aws cloudformation describe-stacks --stack-name my-instances-stack --query 'Stacks[0].Outputs[?OutputKey==`EC2Instance2`].OutputValue' --output text)
          echo "instance_id_2=$id2" >> $GITHUB_ENV


      - name: Реєстрація EC2 інстансів в ECS кластері
        run: |
          instance_arn1=$(aws ecs describe-container-instances --cluster DeepLearnProject --filter "name=ec2InstanceId,values=${{ steps.get-instance-ids.outputs.instance-id-1 }}" --query 'containerInstances[0].containerInstanceArn' --output text)
          instance_arn2=$(aws ecs describe-container-instances --cluster DeepLearnProject --filter "name=ec2InstanceId,values=${{ steps.get-instance-ids.outputs.instance-id-2 }}" --query 'containerInstances[0].containerInstanceArn' --output text)
          aws ecs register-container-instance --cluster DeepLearnProject --container-instance-arn $instance_arn1
          aws ecs register-container-instance --cluster DeepLearnProject --container-instance-arn $instance_arn2

      - name: Розгортання ECS сервісів
        run: |
          aws cloudformation deploy \
          --stack-name my-services-stack \
          --template-file cfecs2.yml \
          --capabilities CAPABILITY_NAMED_IAM


            
            

          
          
