name: loperamid

on:
  push:
    branches:
      - master 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: eu-central-1

      - name: Create EC2 Instances
        id: create-instances
        run: |
          aws cloudformation deploy \
            --stack-name my-instances-stack \
            --template-file cfecs.yml \
            --capabilities CAPABILITY_NAMED_IAM

      - name: Wait for EC2 Instances to be created
        run: |
          aws cloudformation wait stack-create-complete --stack-name my-instances-stack

      - name: Get EC2 Instance IDs
        id: get-instance-ids
        run: |
          id1=$(aws cloudformation describe-stacks --stack-name my-instances-stack --query 'Stacks[0].Outputs[?OutputKey==`EC2Instance1`].OutputValue' --output text)
          echo "instance_id_1=$id1" >> $GITHUB_ENV
          id2=$(aws cloudformation describe-stacks --stack-name my-instances-stack --query 'Stacks[0].Outputs[?OutputKey==`EC2Instance2`].OutputValue' --output text)
          echo "instance_id_2=$id2" >> $GITHUB_ENV

      - name: Register EC2 Instances with ECS Cluster
        run: |
          instance_id_1="${{ steps.get-instance-ids.outputs.instance_id_1 }}"
          instance_id_2="${{ steps.get-instance-ids.outputs.instance_id_2 }}"
          instance_arn1=$(aws ecs describe-container-instances --cluster DeepLearnProject --filter "name=ec2InstanceId,values=$instance_id_1" --query 'containerInstances[0].containerInstanceArn' --output text)
          instance_arn2=$(aws ecs describe-container-instances --cluster DeepLearnProject --filter "name=ec2InstanceId,values=$instance_id_2" --query 'containerInstances[0].containerInstanceArn' --output text)
          aws ecs register-container-instance --cluster DeepLearnProject --container-instance-arn "$instance_arn1"
          aws ecs register-container-instance --cluster DeepLearnProject --container-instance-arn "$instance_arn2"

      - name: Deploy ECS Services
        run: |
          aws cloudformation deploy \
            --stack-name my-services-stack \
            --template-file cfecs2.yml \
            --capabilities CAPABILITY_NAMED_IAM
            
            

          
          
