name: phplogcollector

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment to deploy to'
        required: true
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: eu-central-1

      - name: Create EC2 Instances
        id: create-instances
        run: |
            aws cloudformation deploy \
              --stack-name logcollector \
              --template-file cflogcollect.yml \
              --capabilities CAPABILITY_NAMED_IAM \
              --parameter-overrides Region=eu-central-1


      - name: Get EC2 Instance ID
        id: get-instance-id
        run: |
          INSTANCE_ID=$(aws cloudformation describe-stack-resources --stack-name logcollector --logical-resource-id EC2Instance --query 'StackResources[0].PhysicalResourceId' --output text)
          echo "Instance ID: $INSTANCE_ID"
          echo "::set-output name=instance_id::$INSTANCE_ID"
      
      - name: SSH into EC2 Instance and Retrieve Logs
        if: steps.create-instances.outputs.StackStatus == 'UPDATE_COMPLETE' || steps.create-instances.outputs.StackStatus == 'CREATE_COMPLETE'
        run: |
          INSTANCE_ID="${{ steps.get-instance-id.outputs.instance_id }}"
          PRIVATE_KEY="${{ secrets.AWS_ACCESS_KEY }}" 
          
          # SSH до інстансу і вивести лог у консоль
          ssh -i $PRIVATE_KEY ec2-user@${INSTANCE_ID} 'cat /var/log/phpmyadmin.log'

