name: Manual Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag to use for the Docker image'
        required: true
        default: 'latest'
      
      
      
jobs:

  manual_build_and_push:
    name:  Docker Image Manual Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Build and Push Docker Image
        run: |
          docker image build -t shadowcrosstwink/registry:${{ inputs.tag }} .
          docker push shadowcrosstwink/registry:${{ inputs.tag }}
