name: Manual Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      workflow_name:
        description: 'Name of workflow:'
        required: true
        default: 'shadowmain.yml'
      
      
      
jobs:

  manual_build_and_push:
    name:  Docker Image Manual Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: shadowcrosstwink/registry:${{ inputs.tag }}
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: shadowcrosstwink/registry:${{ inputs.tag }}
