name: Manual Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Enter Docker image tag:'
        required: true
        default: 'latest'
      
      
      
jobs:
  build_and_push_docker_image:
    name:  Auto Build and Push
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install Trivy
      run: |
          sudo apt-get update
          sudo apt-get install wget apt-transport-https gnupg lsb-release -y
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy -y
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    - name: Build the Docker image
      run: |
        docker image build -t shadowcrosstwink/registry:${{ inputs.tag }} .
    - name: Scan Docker image for vulnerabilities
      run: |
        trivy image shadowcrosstwink/registry:${{ inputs.tag }} --format json | tee trivy-report.json
    - name: Upload Trivy report as artifact
      uses: actions/upload-artifact@v2
      with:
        name: Trivy report
        path: trivy-report.json
    - name: Build the Docker image
      run: |
        docker push shadowcrosstwink/registry:${{ inputs.tag }} 
