name: Deploy index.html to Netlify

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Netlify Set Up
        run: |
          npm thatsits
          npm run all

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Netlify
        run: |
          curl -X POST \
               -H "Content-Type: application/zip" \
               -H "Authorization: Bearer ${{ secrets.NETLIFY_SITE_ID }}" \
               --data-binary "@index.html" \
               "https://api.netlify.com/api/v1/sites/${{ secrets.NETLIFY_SITE_ID }}/deploys"


