name: Docker Build and Push

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  DOCKER_USERNAME: ${{ secrets.shadowcrosstwink }}
  DOCKER_PASSWORD: ${{ secrets.Arsenii89890076 }}
  DOCKER_REGISTRY: https://registry.hub.docker.com

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.DOCKER_REGISTRY }}
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ${{ env.DOCKER_REGISTRY }}/my-image:${{ github.sha }}
          ${{ env.DOCKER_REGISTRY }}/my-image:latest
  build-and-push-manual:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
     

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.DOCKER_REGISTRY }}
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ${{ env.DOCKER_REGISTRY }}/my-image:${{ github.run_id }}-${{ inputs.tag }}
          ${{ env.DOCKER_REGISTRY }}/my-image:${{ inputs.tag }}
