name: Build and Push Docker Image

on:
  push:
    branches:
      - master
  workflow_dispatch:


jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          
      - name: TEST secrets
        run: echo ${{ secrets.DOCKER_USERNAME }} & echo ${{ secrets.DOCKER_PASSWORD }} & echo ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: sudosu
        run: sudo su
      - name: apt-utils
        run: sudo apt-get install apt-utils
      - name: Build Docker image
        run: docker build -t shadowcrosstwink/registry .
      - name: Push Docker image
        run: push shadowcrosstwink/registry
      

  manual_build_and_push_docker_image:
    name: Manual Build and Push Docker Image
    needs: []
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    
