name: Auto Build and Push Image with hashtag

on:
  push:
    branches:
      - master
  workflow_dispatch:
    

      
jobs:
  build_and_push_docker_image:
    name:  Auto Build and Push
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}  
    - name: Build the Docker image
      run: |
        docker image build -t shadowcrosstwink/registry:${{ github.sha }} .
    - name: Scan Docker image
      uses: aquasecurity/trivy-action@v2
      with:
        image-ref: shadowcrosstwink/registry:${{ github.sha }}
        exit-code-on-high-severity: 1
    - name: Push the Docker image
      run: |
        docker push shadowcrosstwink/registry:${{ github.sha }}
    - name: Save Trivy report
      uses: actions/upload-artifact@v2
      with:
        name: trivy-report
        path: /tmp/trivy
      
        
