name: Build and Push Docker Image

on:
  push:
    branches:
      - master
  workflow_dispatch:


jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          
      - name: TEST secrets
        run: echo ${{ secrets.DOCKER_USERNAME }} & echo ${{ secrets.DOCKER_PASSWORD }} & echo ${{ secrets.DOCKER_ACCESS_TOKEN }}
     
      

  manual_build_and_push_docker_image:
    name: Manual Build and Push Docker Image
    needs: []
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    - name: Build Docker image
      run: docker build -t shadowcrosstwink/registry
    - name: Push Docker image
      run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} shadowcrosstwink
          docker tag shado shadowcrosstwink/registry:latest
          docker push shadowcrosstwink/registry:latest
