name: Build and Push Docker Image

on:
  push:
    branches:
      - master
  workflow_dispatch:
  
    

jobs:
  build_and_push_docker_image:
    name:  JOB
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        
    - name: Build the Docker image
      run: |
        docker image build -t shadowcrosstwink/registry .
        docker push shadowcrosstwink/registry
        
        
  manual_input_job:
    name:  MANUAL
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    - name: Build the Docker image
      run: |
        docker image build -t shadowcrosstwink/registry .
        docker push shadowcrosstwink/registry
    
